## THE TITANIC DATASET

**Importing the necessarry libraris**


Pandas for data exploration and analysis


numpy for mathematical calculations

In [91]:
import pandas as pd
import numpy as np

**Load the dataset**


loading the dataset from an Url

In [92]:
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
df = pd.read_csv(url)

**Dataset Review and Exploration**

We want to know details about the dataset includng:

columns and its data types,

number of colmns and rows,

null values present in the dataset,

In [93]:
#viewing first five rows of the dataset
df.head(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [94]:
#viewing the number of rows and columns
df.shape

(891, 12)

In [95]:
#viewing the collums, their datatypes and the total nun null valus in each
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [96]:
#viewing the  statistical analysis of the dataset
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

looking for null values

In [97]:
#finding the sum of all null values
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

**Data Exploration for target valriables**

The "survived" column is our target variable, encoded, such that

0 - People thaht died in the titanic

1 - People that survived in the titanic

In [98]:
df['Survived'].value_counts()

Survived
0    549
1    342
Name: count, dtype: int64

In [99]:
#checking the data types of the column
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

**Data cleaning and preparation**

This process inclueds filling nun null values and /or dropping columns

In [100]:
# Fill null values in the Age column with median age
df["Age"] = df["Age"].fillna(df["Age"].median())

# Fill the null values in the Embarked column with mode
df["Embarked"] = df["Embarked"].fillna(df["Embarked"].mode()[0])

# Since the Cabin column has too many missing values(600+), we drop it!
df = df.drop("Cabin", axis=1)

**Encoding**

Since we have categorical data, we are going to do one hot encoding, so hat our model works efficiently

We will encode the female column, such that:

1 - female passengers

2- male passengers

In [101]:
# Convert Sex to numeric
df["Sex"] = df["Sex"].map({"male": 0, "female": 1})

# One-hot encode Embarked
df = pd.get_dummies(df, columns=["Embarked"], drop_first=True)

In [102]:
#dropping non numerical data
df = df.drop(["Name", "Ticket", "PassengerId"], axis=1)

In [103]:
#viewing any non null values
df.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age           0
SibSp         0
Parch         0
Fare          0
Embarked_Q    0
Embarked_S    0
dtype: int64

**Splitting and Training data**

We define X and Y such that:

y - contains the target variable which we what to predict which is the survived colmn

x - contains allt he other variables(colums)

In [104]:
#definig x an d y
X = df.drop('Survived', axis=1)
y = df['Survived']

Import the splitting fuction from sklearn

We split the data

In [105]:
#imporing the splitting method
from sklearn.model_selection import train_test_split

#splitting the data
X_train,X_test, Y_train, Y_test = train_test_split(X, y , test_size=0.2, random_state=42)

**LOGISTICS MODEL**

-import the logistics model

-create an instance for the model

-fit the model

In [106]:
#import the model
from sklearn.linear_model import LogisticRegression

#instance for the model
model = LogisticRegression(max_iter=1000)

#fitting the model
model.fit(X_train, Y_train)

LogisticRegression(max_iter=1000)

**METRICS**

We import the metrics, which are used to measure the prediction accuracy for the model

In [107]:
#import the accuracy_score function from the metrics module in the sklearn library
from sklearn.metrics import accuracy_score

#define a variable that contains the predicted values
Y_pred = model.predict(X_test)

#alooking for metrics using the accuracy_score function
accuracy = accuracy_score(Y_test, Y_pred)

print("Accuracy:", accuracy)

Accuracy: 0.8100558659217877

Purpose of the classification report is to give us more metric information, based through:

F1 SCORE

Precision

Recall

In [108]:
from sklearn.metrics import classification_report

print(classification_report(Y_test, Y_pred))

              precision    recall  f1-score   support

           0       0.83      0.86      0.84       105
           1       0.79      0.74      0.76        74

    accuracy                           0.81       179
   macro avg       0.81      0.80      0.80       179
weighted avg       0.81      0.81      0.81       179

We import the confusion_matrix to help us nderstand the model perfomance in terms of:

-Correct predictions

-Incorrect Predictions

In [109]:
from sklearn.metrics import confusion_matrix

confusion_matrix(Y_test, Y_pred)

array([[90, 15],
       [19, 55]])

**Making Predictions**

In [110]:
# Select sample
sample = X_test.iloc[[0]]  # keep as DataFrame
sample

     Pclass  Sex   Age  SibSp  Parch     Fare  Embarked_Q  Embarked_S
709       3    0  28.0      1      1  15.2458       False       False

In [111]:
# Make prediction
prediction = model.predict(sample)
print("Prediction:", prediction)

Prediction: [0]

In [114]:
# Compare with actual
print("Actual:", Y_test.iloc[0])

Actual: 1

**Understanding Predictions**

In [115]:
for i in range(5):
    sample = X_test.iloc[[i]]
    pred = model.predict(sample)[0]
    actual = Y_test.iloc[i]

    print(f"Passenger {i}: Prediction={pred}, Actual={actual}")

Passenger 0: Prediction=0, Actual=1
Passenger 1: Prediction=0, Actual=0
Passenger 2: Prediction=0, Actual=0
Passenger 3: Prediction=1, Actual=1
Passenger 4: Prediction=1, Actual=1